### ISSUE TITLE
Parsing a model with an extension extends the extension by itself

### ISSUE THREAD

**Issue by verbitan** [yaal-coop/scim2-models#63]
When parsing JSON into a model, if that model contains an extension, the extension class on the model is extended by itself.

Take the following simple example:
```python
user = User[EnterpriseUser].model_validate(
    {
        "schemas": [
            "urn:ietf:params:scim:schemas:core:2.0:User",
            "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User",
        ],
        "userName": "Test.User@example.com",
        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": {
            "employeeNumber": "12345",
        },
    }
)

print(user)
```

This currently prints the following:
> schemas=['urn:ietf:params:scim:schemas:core:2.0:User', 'urn:ietf:params:scim:schemas:extension:enterprise:2.0:User'] id=None external_id=None meta=None user_name='Test.User@example.com' name=None display_name=None nick_name=None profile_url=None title=None user_type=None preferred_language=None locale=None timezone=None active=None password=None emails=None phone_numbers=None ims=None photos=None addresses=None groups=None entitlements=None roles=None x509_certificates=None EnterpriseUser=EnterpriseUser[EnterpriseUser](schemas=['urn:ietf:params:scim:schemas:extension:enterprise:2.0:User'], id=None, external_id=None, meta=None, employee_number='12345', cost_center=None, organization=None, division=None, department=None, manager=None, EnterpriseUser=None)

Whereas I'd expect it to print:
> schemas=['urn:ietf:params:scim:schemas:core:2.0:User', 'urn:ietf:params:scim:schemas:extension:enterprise:2.0:User'] id=None external_id=None meta=None user_name='Test.User@example.com' name=None display_name=None nick_name=None profile_url=None title=None user_type=None preferred_language=None locale=None timezone=None active=None password=None emails=None phone_numbers=None ims=None photos=None addresses=None groups=None entitlements=None roles=None x509_certificates=None EnterpriseUser=EnterpriseUser(schemas=['urn:ietf:params:scim:schemas:extension:enterprise:2.0:User'], id=None, external_id=None, meta=None, employee_number='12345', cost_center=None, organization=None, division=None, department=None, manager=None)

Note `EnterpriseUser=EnterpriseUser[EnterpriseUser](...)` vs. `EnterpriseUser=EnterpriseUser(...)`.

**Comment by azmeuk** [comment]
Thank you for your bug report.
Indeed, with your sample we have this, that is problematic:
```python
>>> type(user[EnterpriseUser])
<class 'scim2_models.rfc7643.enterprise_user.EnterpriseUser[EnterpriseUser]'>
```

It seems to be related to #54 and [this issue in pydantic](https://github.com/pydantic/pydantic/issues/9858).
I am not sure how yet, but this is definitively something we have to fix.
